recipients:
- name: admin
  public_key: age1se1qf03dka0acmtv853prprnq5kf5gcpcv7dfafnfltqp07lp79z5avsuamhk6
  username: kig
  break_glass: false
- name: break-glass
  public_key: age16njzjmtuae0f8p82tu7uuyd25m28qr2jnfdm08cmt9em77xrhchslufj8n
  break_glass: true
encrypted_globs:
- '*.encrypted'
- .env.encrypted
- config/*.encrypted.yaml
sops_version: 3.13.2
join_request_ttl: 72h
